### PR TITLE
PostGis Shipping Location Implementation [WIP]

### PR DESCRIPTION
**Pull request by AbdulrahmanDaud10**
# What this PR does:
* Implement locational shipping feature using `PostGis`

### CODE REVIEW

**Review by wisemiro — APPROVED** [review]
All good, though there shouldn't be a Geo table, rather only a model.

**Comment by AbdulrahmanDaud10** [comment]
` geo bigint constraint fk_location-shipping_id references geos,`
* If I don't make the Geo struct as a table is this referencing okay?
* And the struck to be:
````
type Geo struct {
	Latitude  float64 `json:"latitude" `
	Longitude float64 `json:"longitude"`
}
````

**Comment by wisemiro** [comment]
change: geo bigint constraint fk_location-shipping_id references geos
to: location      geometry(POINT) not null

**Comment by AbdulrahmanDaud10** [comment]
`location geometry(POINT) not null` already implemented

**Pull request merged**
